# fly.toml app configuration file generated for sp-daily-memo on 2026-03-03T20:59:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sp-daily-memo'
primary_region = 'iad'

[build]

[env]
  DB_PATH = "/data/camp_manager.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "camp_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
